#!/bin/bash
set -euo pipefail

# Usage check
if [[ $# -ne 3 ]]; then
    echo "Usage: $0 <coverage_summary.tsv> <cutoffs.txt> <output.pdf>"
    exit 1
fi

tsv_file="$1"
cutoffs_file="$2"
pdf_file="$3"

html_file=$(mktemp --suffix=.html)

declare -A cutoffs

# Read cutoffs file into associative array
while IFS='=' read -r key val; do
    key=$(echo "$key" | xargs)   # trim whitespace
    val=$(echo "$val" | xargs)
    cutoffs[$key]=$val
done < "$cutoffs_file"

# Assign variables from cutoffs
min_total_reads=${cutoffs["total"]}
min_mean_depth=${cutoffs["Mean Depth"]}
min_median_depth=${cutoffs["Median Depth"]}
min_breadth_1x=${cutoffs["Breadth_1x"]}
min_breadth_10x=${cutoffs["Breadth_10x"]}

any_fail=0

# Start HTML
cat <<EOF > "$html_file"
<html>
<head>
<meta charset='UTF-8'>
<style>
body { font-family: Arial, sans-serif; margin-bottom: 40px; }
table, th, td { border: 1px solid black; border-collapse: collapse; padding: 6px; text-align: center; }
th { background-color: #f2f2f2; }
.fail { background-color: #ffcccc; }
.pass { background-color: #ccffcc; }
.warning { color: red; font-weight: bold; margin-top: 20px; }
.footer {
    font-size: 14px;
    color: #444444;
    text-align: right;
    margin-top: 40px;
    font-style: italic;
}
</style>
</head>
<body>
<h2>Coverage Summary Report</h2>
<p><strong>Thresholds:</strong></p>
<ul>
    <li>Total Reads (millions) ≥ <strong>$min_total_reads</strong></li>
    <li>Mean Depth ≥ <strong>$min_mean_depth</strong></li>
    <li>Median Depth ≥ <strong>$min_median_depth</strong></li>
    <li>Breadth 1x ≥ <strong>$min_breadth_1x</strong></li>
    <li>Breadth 10x ≥ <strong>$min_breadth_10x</strong></li>
</ul>
<table>
EOF

# Read header
IFS=$'\t' read -r -a headers < "$tsv_file"
echo "<tr>" >> "$html_file"
for col in "${headers[@]}"; do
    echo "<th>${col}</th>" >> "$html_file"
done
echo "</tr>" >> "$html_file"

# Process data rows
tail -n +2 "$tsv_file" > tmp_data.tsv
while IFS=$'\t' read -r sample total_reads_m mapped_reads_m mean_depth median_depth min_depth max_depth breadth_1x breadth_10x; do
    echo "<tr>" >> "$html_file"
    echo "<td>${sample}</td>" >> "$html_file"

    # Total Reads (in millions)
    if (( $(echo "$total_reads_m >= $min_total_reads" | bc -l) )); then
        echo "<td class='pass'>$total_reads_m</td>" >> "$html_file"
    else
        echo "<td class='fail'>$total_reads_m</td>" >> "$html_file"
        any_fail=1
    fi

    # Mapped Reads
    echo "<td>${mapped_reads_m}</td>" >> "$html_file"

    # Mean Depth
    if (( $(echo "$mean_depth >= $min_mean_depth" | bc -l) )); then
        echo "<td class='pass'>$mean_depth</td>" >> "$html_file"
    else
        echo "<td class='fail'>$mean_depth</td>" >> "$html_file"
        any_fail=1
    fi

    # Median Depth
    if (( $(echo "$median_depth >= $min_median_depth" | bc -l) )); then
        echo "<td class='pass'>$median_depth</td>" >> "$html_file"
    else
        echo "<td class='fail'>$median_depth</td>" >> "$html_file"
        any_fail=1
    fi

    # Min and Max Depth (no check)
    echo "<td>${min_depth}</td><td>${max_depth}</td>" >> "$html_file"

    # Breadth 1x
    if (( $(echo "$breadth_1x >= $min_breadth_1x" | bc -l) )); then
        echo "<td class='pass'>$breadth_1x</td>" >> "$html_file"
    else
        echo "<td class='fail'>$breadth_1x</td>" >> "$html_file"
        any_fail=1
    fi

    # Breadth 10x
    if (( $(echo "$breadth_10x >= $min_breadth_10x" | bc -l) )); then
        echo "<td class='pass'>$breadth_10x</td>" >> "$html_file"
    else
        echo "<td class='fail'>$breadth_10x</td>" >> "$html_file"
        any_fail=1
    fi

    echo "</tr>" >> "$html_file"
done < tmp_data.tsv
rm -f tmp_data.tsv

echo "</table>" >> "$html_file"

# Coverage interpretation
if [[ $any_fail -eq 1 ]]; then
    echo "<p class='warning'>Sample Not of Adequate coverage or depth, Not recommended to include in reports or for any further microbiome interpretations. If sample is NTC then it shows that there is no significant microbiome lab contamination.</p>" >> "$html_file"
else
    echo "<p style='color:green; font-weight:bold; margin-top: 20px;'>The sample is of Adequate coverage or depth and can be considered for further microbiome interpretations.</p>" >> "$html_file"
fi

cat <<EOF >> "$html_file"
<div class="footer">
Report generated by ACTREC Rifaximin Clinical Trial Bioinformatics Pipeline hosted at https://github.com/arpit20328/Nextflow-Pipeline-for-16S-Nanopore-Data-Analysis. For any query please contact Dr Anant Gokarn at anantgokarn@gmail.com.
</div>
</body></html>
EOF

wkhtmltopdf "$html_file" "$pdf_file" > /dev/null 2>&1
echo "PDF generated at: $pdf_file"
rm -f "$html_file"

